
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import static org.bouncycastle.crypto.modes.kgcm.KGCMUtil_128.x;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HiTech
 */
public class billing2 extends javax.swing.JFrame {

    /**
     * Creates new form billing
     */
    public billing2() {
        initComponents();
             ids();
        dele();
       data();
      
   
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
double x,y,z,per,xy;


public void dele()
{
   String sql="Delete from bill where billno=?";
try
{
 Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, bno.getText());
              pst.executeUpdate();
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e);
} 
}

    
 public void report() throws JRException  
{
    repos.setVisible(true);
    try{
    Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
    HashMap a=new HashMap();
    a.put("invo", bno.getText());
    pan.removeAll();
    pan.repaint();
    pan.revalidate();
    
    JasperDesign jd=JRXmlLoader.load("src\\report1.jrxml"
            + "");
    JasperReport jr=JasperCompileManager.compileReport(jd);
    JasperPrint jp=JasperFillManager.fillReport(jr,a,con);
    JRViewer v=new JRViewer(jp);
    pan.setLayout(new BorderLayout());
    pan.add(v);
    }
    catch(ClassNotFoundException | SQLException | JRException e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
}
    
     public void ids()
        {
            int tid=1;

        PreparedStatement pst=null;
        ResultSet  rs=null;

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            pst=con.prepareStatement("Select MAX(bno) from billing");
            rs=pst.executeQuery();
            while(rs.next())
            {
                tid=rs.getInt(1);
                tid++;
            }
            String val;
            val=String.valueOf(tid);
            bno.setText(val);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
            
        }
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repos = new javax.swing.JFrame();
        pan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pname = new javax.swing.JTextArea();
        sgst = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        subt = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        rt = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cgst = new javax.swing.JTextField();
        hsn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        bno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cont = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        cou = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gst = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        repos.setMinimumSize(new java.awt.Dimension(1000, 1000));
        repos.getContentPane().add(pan, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 180, 100, 30);

        pname.setColumns(20);
        pname.setRows(5);
        jScrollPane1.setViewportView(pname);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 430, 330, 70);

        sgst.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(sgst);
        sgst.setBounds(680, 320, 320, 30);

        jLabel34.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Rate");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(550, 90, 110, 30);

        tot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tot.setText("0");
        jPanel1.add(tot);
        tot.setBounds(680, 490, 320, 30);

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 490, 90, 30);

        jLabel36.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Tax");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(560, 400, 100, 30);

        tax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(tax);
        tax.setBounds(680, 400, 320, 30);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SGST");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(550, 320, 100, 30);

        subt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        subt.setText("0");
        subt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtActionPerformed(evt);
            }
        });
        jPanel1.add(subt);
        subt.setBounds(680, 360, 320, 30);

        jLabel33.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Count");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(550, 130, 90, 30);

        rt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtActionPerformed(evt);
            }
        });
        jPanel1.add(rt);
        rt.setBounds(680, 90, 320, 30);

        jButton16.setBackground(new java.awt.Color(255, 51, 102));
        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton16.setText("Add");
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(780, 440, 110, 40);

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 250, 100, 30);

        add.setColumns(20);
        add.setRows(5);
        jScrollPane2.setViewportView(add);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(160, 230, 330, 70);

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sub-Total");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(550, 360, 100, 30);

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CGST");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(550, 280, 100, 30);

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("HSN/SAC");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(550, 50, 100, 30);

        cgst.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(cgst);
        cgst.setBounds(680, 280, 320, 30);

        hsn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(hsn);
        hsn.setBounds(680, 50, 320, 30);

        jLabel16.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Destination");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 330, 120, 30);

        des.setColumns(20);
        des.setRows(5);
        jScrollPane3.setViewportView(des);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(160, 320, 330, 70);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 80, 30);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bill number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 50, 120, 34);

        name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(name);
        name.setBounds(160, 90, 320, 30);

        bno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(bno);
        bno.setBounds(160, 50, 320, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 80, 30);

        cont.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(cont);
        cont.setBounds(160, 140, 320, 30);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 430, 150, 30);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tab);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(490, 600, 690, 210);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(540, 540, 130, 40);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(700, 540, 130, 40);

        date.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(date);
        date.setBounds(160, 180, 320, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(870, 540, 120, 40);

        cou.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(cou);
        cou.setBounds(680, 130, 320, 30);

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("GST Per");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(550, 170, 100, 30);

        gst.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gstKeyPressed(evt);
            }
        });
        jPanel1.add(gst);
        gst.setBounds(680, 170, 320, 30);

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter Button for GST Calculation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 220, 260, 40);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(0, 0, 1900, 970);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1970, 1270);

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 170, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private static String input;
    private static int num;
    private static String[] units=
    {"",
     " One",
     " Two",
     " Three",
     " Four",
     " Five",
     " Six",
     " Seven",
     " Eight",
     " Nine"
    };
    private static String[] teen=
   {" Ten",
    " Eleven",
    " Twelve",
    " Thirteen",
    " Fourteen",
    " Fifteen",
    " Sixteen",
    " Seventeen",
    " Eighteen",
    " Nineteen"
   };
   private static String[] tens=
  { " Twenty",
    " Thirty",
    " Forty",
    " Fifty",
    " Sixty",
    " Seventy",
    " Eighty",
    " Ninety"
  };
  private static String[] maxs=
 {"",
  "",
  " Hundred",
  " Thousand",
  " Lakh",
  " Crore"
 };

    
    public String convertNumberToWords(double n)
    {
        input=numToString((int) n);
        String converted=""; 
        int pos=1; 
        boolean hun=false;
        while(input.length()> 0)
        {
            if(pos==1) // TENS AND UNIT POSITION
            {   if(input.length()>= 2) // TWO DIGIT NUMBERS
                {   
                 String temp=input.substring(input.length()-2,input.length());
                 input=input.substring(0,input.length()-2);
                 converted+=digits(temp);
                }
                else if(input.length()==1) // 1 DIGIT NUMBER
                {
                 converted+=digits(input); 
                 input="";
                }
                pos++;
            }
            else if(pos==2) // HUNDRED POSITION
            { 
                String temp=input.substring(input.length()-1,input.length());
                input=input.substring(0,input.length()-1);
                if(converted.length()> 0&&digits(temp)!="")
                {
                    converted=(digits(temp)+maxs[pos]+" and")+converted;
                    hun=true;
                }
                else
                {
                    if
                    (digits(temp)=="");
                    else
                    converted=(digits(temp)+maxs[pos])+converted;hun=true;
                }
                pos++;
            }
            else if(pos > 2) // REMAINING NUMBERS PAIRED BY TWO
            {
                if(input.length()>= 2) // EXTRACT 2 DIGITS
                {  
                 String temp=input.substring(input.length()-2,input.length());
                 input=input.substring(0,input.length()-2);
                   if(!hun&&converted.length()> 0)
                        converted=digits(temp)+maxs[pos]+" and"+converted;
                    else
                    {
                        if(digits(temp)=="")  ;
                        else
                        converted=digits(temp)+maxs[pos]+converted;
                    }
                 }
                 else if(input.length()==1) // EXTRACT 1 DIGIT
                 {
                   if(!hun&&converted.length()> 0)
                    converted=digits(input)+maxs[pos]+" and"+converted;
                    else
                    {
                        if(digits(input)=="")  ;
                        else
                        converted=digits(input)+maxs[pos]+converted;
                        input="";
                    }
                 }
                 pos++; 
             }
        }
        return converted;
    }
    private String digits(String temp) // TO RETURN SELECTED NUMBERS IN WORDS
    {
        String converted="";
        for(int i=temp.length()-1;i >= 0;i--)
        {   int ch=temp.charAt(i)-48;
            if(i==0&&ch>1 && temp.length()> 1)
            converted=tens[ch-2]+converted; // IF TENS DIGIT STARTS WITH 2 OR MORE IT FALLS UNDER TENS
            else if(i==0&&ch==1&&temp.length()==2) // IF TENS DIGIT STARTS WITH 1 IT FALLS UNDER TEENS
            {
                int sum=0;
                for(int j=0;j < 2;j++)
                sum=(sum*10)+(temp.charAt(j)-48);
                return teen[sum-10];
            }
            else
            {
                if(ch > 0)
                converted=units[ch]+converted;
            } // IF SINGLE DIGIT PROVIDED
        }
        return converted;
    }
    private String numToString(int x) // CONVERT THE NUMBER TO STRING
    {
        String num="";
        while(x!=0)
        {
            num=((char)((x%10)+48))+num;
            x/=10;
        }
        return num;
    }
    private void inputNumber()
    {
        Scanner in=new Scanner(System.in);
        try
        {
          System.out.print("Please enter number to Convert into Words : ");
          num=in.nextInt();
        }
        catch(Exception e)
        {
         System.out.println("Number should be Less than 1 Arab ");
         System.exit(1);
        }
    }
  
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
adddata();
data();
totalf();
clear();
    }//GEN-LAST:event_jButton16ActionPerformed
 public void data()
    {
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            String sql="Select billno,hsn,product,rate,count,cgst,sgst,gst,subtotal from bill where billno=?";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,bno.getText());
            ResultSet rs=pst.executeQuery();
            tab.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }double itotal;public void clear()
{
    pname.setText("");
    rt.setText("");
    hsn.setText("");
    cou.setText("");
    gst.setText("");
}
    
    public void totalf()
{
    
   try
        {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            String sql="Select sum(subtotal),sum(tax) from bill where billno='"+bno.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
                String sum=rs.getString("sum(subtotal)");
                String gst_val=rs.getString("sum(tax)");
               itotal=Double.parseDouble(sum);
              
            double dd,tt,tk;   
            dd=Double.parseDouble(gst_val);
            tk=dd+itotal;
            tot.setText(String.format("%.2f", tk));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }  
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         cgsttot();
  sgsttot();
  sutot();
  store();
        String ffd=tot.getText();
         String ff=tax.getText();
          String amx,mx;
  double aamt,at,aa,ab,ac;
   aamt = Double.parseDouble(ffd);
   at = Double.parseDouble(ff);
    amx= convertNumberToWords(aamt)+" Rupees Only";
     mx= convertNumberToWords(at)+" Rupees Only";
        try
          {
              
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");

            String sql="Insert into billing(bno,name,contact,date,address,dest,pname,count,cgst,sgst,hsn,subtotal,tax,total,rate,srno,irate,iitem,icount,icgst,isgst,ihsn,itax,isubt,words,tword,itax1) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);

            pst.setString(1,bno.getText());
            pst.setString(2,name.getText());
            pst.setString(3,cont.getText());
            SimpleDateFormat sdf= new SimpleDateFormat ("dd/MM/yyyy");
            String dt= sdf.format(date.getDate());
            pst.setString(4,dt);
            pst.setString(5,add.getText());
            pst.setString(6,des.getText());
          pst.setString(7,pname.getText());
         // pst.setString(7,pname.getText());
     //       pst.setString(8,brand.getSelectedItem().toString());
            pst.setString(8,rt.getText());
            pst.setString(9,cgst.getText());
            pst.setString(10,sgst.getText());
            pst.setString(11,hsn.getText()); 
            pst.setString(12,subt.getText());
            pst.setString(13,tax.getText());
            pst.setString(14,tot.getText());
            
          //  pst.setString(17,amtt.getText());
            pst.setString(15,rt.getText());
            pst.setString(16,f10);
            pst.setString(17,f3);
            pst.setString(18,f2);
            pst.setString(19,f4);
            pst.setString(20,f5);
            pst.setString(21,f6);
            pst.setString(22,f1);
            pst.setString(23,f7);
            pst.setString(24, f8);
            pst.setString(25, amx);
            pst.setString(26, mx);
            pst.setString(27, f9);
            
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null,"Add Successfully...");
             report();
            bno.setText("");
            name.setText("");
            cont.setText("");
            add.setText("");
            des.setText("");
            pname.setText("");
           // pname.setText("");
            rt.setText("");
            cgst.setText("");
            sgst.setText("");
           hsn.setText("");
           subt.setText("");
           tax.setText("");
           tot.setText("");
           amx="";
            mx="";
         //  amtt.setText("");
           rt.setText("");
            f1="";
           f2="";
            reset();
           ids();
            empmenu1 i=new  empmenu1();
        i.setVisible(true);
        dispose();
         }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(null,e);
         
          }

    }//GEN-LAST:event_jButton2ActionPerformed
 String cg="",sg="",subto="",taxx="";
    public void cgsttot()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            String sql="Select sum(cgst) from bill where billno='"+bno.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
               cgst.setText(rs.getString("sum(cgst)"));
               
            }
        }
        catch(Exception e)
        {
            
        }
    }
    
     public void sgsttot()
{
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            String sql="Select sum(sgst) from bill where billno='"+bno.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
              sgst.setText(rs.getString("sum(sgst)"));
               
            }
        }
        catch(Exception e)
        {
            
        }

}
     public void sutot()
{
    try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            String sql="Select sum(subtotal),sum(tax) from bill where billno='"+bno.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
               subt.setText(rs.getString("sum(subtotal)"));
              tax.setText(rs.getString("sum(tax)"));
               
            }
        }
        catch(Exception e)
        {
            
        }
}
    private void subtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     User_login i=new  User_login();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
public void reset()
{
                name.setText("");
            cont.setText("");
            add.setText("");
            des.setText("");
           
            rt.setText("");
            cgst.setText("");
            sgst.setText("");
           hsn.setText("");
           subt.setText("");
           tax.setText("");
           tot.setText("");
           
           pname.setText("");
           rt.setText("");
           data();
               irate.clear();
    icount.clear();
    icgst.clear();
    isgst.clear();
    igst.clear();
    isubtot.clear();
    ihsn.clear();
    itax.clear();
     itax1.clear();
           f3="";f4="";f5="";f6="";f7="";f8="";f9="";f10="";f11="";
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     reset();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtActionPerformed
       
      
    }//GEN-LAST:event_rtActionPerformed

ArrayList<String> iproduct = new ArrayList<>();
//ArrayList<String> ibrand = new ArrayList<>();
ArrayList<String> irate = new ArrayList<>();
ArrayList<String> icount = new ArrayList<>();
ArrayList<String> icgst = new ArrayList<>();
ArrayList<String> isgst = new ArrayList<>();
ArrayList<String> igst = new ArrayList<>();
ArrayList<String> isubtot = new ArrayList<>();
ArrayList<String> ihsn = new ArrayList<>();
ArrayList<String> itax = new ArrayList<>();
ArrayList<String> itax1 = new ArrayList<>();
String f1="",f2="",f3="",f4="",f5="",f6="",f7="",f8="",f9="",f10="",f11="";
int klk=0;
public void store()
{
    billda();
   int cout=ihsn.size();
   for(int kgf=0;kgf<cout;kgf++)
   {
       f1+=ihsn.get(kgf)+"\n\n";
       f2+=iproduct.get(kgf)+"\n\n";
       f3+=irate.get(kgf)+"\n\n";
       f4+=icount.get(kgf)+"\n\n";
       f5+=icgst.get(kgf)+"\n\n";
       f6+=isgst.get(kgf)+"\n\n";
       f7+=igst.get(kgf)+"\n\n";
       f8+=isubtot.get(kgf)+"\n\n";
       f9+=itax1.get(kgf)+"\n\n";
       klk+=1;
       f10+=String.valueOf(klk)+"\n\n";
       
   }
   
}

public void billda()
{
    String sql="SELECT * from bill where billno='"+bno.getText()+"'";
       try {
            
        Class.forName("com.mysql.jdbc.Driver");
            Connection conc=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
   
PreparedStatement pst=conc.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
             while(rs.next())
             {
                 
                 ihsn.add(rs.getString("hsn"));
                 iproduct.add(rs.getString("product"));
             //    ibrand.add(rs.getString("brand"));
                 icgst.add(rs.getString("cgst"));
                 isgst.add(rs.getString("sgst"));
                 igst.add(rs.getString("gst"));
                 isubtot.add(rs.getString("subtotal"));
                 irate.add(rs.getString("rate"));
                 icount.add(rs.getString("count"));
                 itax.add(rs.getString("tax"));
                  itax1.add(rs.getString("tax")); 
                
        }
       }
             catch (ClassNotFoundException | SQLException e) {
                 JOptionPane.showMessageDialog(null, e);
        }
}




public void adddata()
{
    String ffd=tax.getText();
          String amx;
  double aamt,aa,ab,ac;
   aamt = Double.parseDouble(ffd);
    amx= convertNumberToWords(aamt)+" Rupees Only";
 try
        {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jesh","root","hitech");
            String sql="Insert into bill(billno,hsn,product,rate,count,cgst,sgst,gst,subtotal,tax,word) values(?,?,?,?,?,?,?,?,?,?,?)";
           PreparedStatement pst=con.prepareStatement(sql);
           
            pst.setString(1,bno.getText());
            pst.setString(2,hsn.getText());
            pst.setString(3,pname.getText());
            pst.setString(4, rt.getText());
            pst.setString(5,cou.getText());
            pst.setString(6,cgst.getText());
            pst.setString(7, sgst.getText());
            pst.setString(8, gst.getText());
             pst.setString(9, subt.getText());
            pst.setString(10, tax.getText());
            pst.setString(11, amx);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Add Successfully...");

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);

        }
}
    private void gstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gstKeyPressed
      
         x=Double.parseDouble(rt.getText());
        int qnt,gt;
        qnt=Integer.parseInt(cou.getText());
       
        double dd;
 
        
        
        
     if(evt.getKeyCode()==KeyEvent.VK_ENTER)
                
                      y=x*qnt; // y => rate * quantity
                      subt.setText(String.format("%.2f", y)); // sub total amount
                         gt=Integer.parseInt(gst.getText());  
                         dd=y*gt/100; // calculate gstr amount
                         double cg;
                         cg=dd/2; // cgst and sgst
                         tax.setText(String.format("%.2f", dd));
                         cgst.setText(String.format("%.2f", cg));
                         sgst.setText(String.format("%.2f", cg));
                         double tt =Double.parseDouble(tot.getText());
                         tt=y+dd;
                      
                         
                         tot.setText(String.format("%.2f",tt));
    }//GEN-LAST:event_gstKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
         x=Double.parseDouble(rt.getText());
        int qnt,gt;
        qnt=Integer.parseInt(cou.getText());
       
        double dd;
 
        
        
        
     //   if(evt.g==KeyEvent.VK_ENTER)
                
                      y=x*qnt; // y => rate * quantity
                      subt.setText(String.format("%.2f", y)); // sub total amount
                         gt=Integer.parseInt(gst.getText());  
                         dd=y*gt/100; // calculate gstr amount
                         double cg;
                         cg=dd/2; // cgst and sgst
                         tax.setText(String.format("%.2f", dd));
                         cgst.setText(String.format("%.2f", cg));
                         sgst.setText(String.format("%.2f", cg));
                         double tt =Double.parseDouble(tot.getText());
                         tt=y+dd;
                      
                         
                         tot.setText(String.format("%.2f",tt));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JTextField bno;
    private javax.swing.JTextField cgst;
    private javax.swing.JTextField cont;
    private javax.swing.JTextField cou;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextArea des;
    private javax.swing.JTextField gst;
    private javax.swing.JTextField hsn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField name;
    private javax.swing.JPanel pan;
    private javax.swing.JTextArea pname;
    private javax.swing.JFrame repos;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField sgst;
    private javax.swing.JTextField subt;
    private javax.swing.JTable tab;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
