


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HiTech
 */
public class homepage extends javax.swing.JFrame {
public homepage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        cb.setEnabled(true);
        data();
    }
public void data()
{
     Date d=new Date();
       SimpleDateFormat s=new SimpleDateFormat("dd/MM/yyyy");
       
        String startDate=s.format(d);
        String endDate="30/09/2022";
        try
        {
            
        
        try {
            Date start = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH)
                    .parse(startDate);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        try {
            Date end = new SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH)
                    .parse(endDate);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
         SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

    Date date1 = null,date2 = null;
        try {
            date1 = format.parse(startDate);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    
        try {
            date2 = format.parse(endDate);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
        if(date1.after(date2))
        {
             JOptionPane.showMessageDialog(null,"Trial Expired");
             cb.setEnabled(false);
        }
        if(date1.equals(date2))
        {
            JOptionPane.showMessageDialog(null,"Your Trial Version Going to End Today");
            cb.setEnabled(true);
        }
    
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e);
        }
}
    /**
     * Creates new form homepage
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile:9840264992");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(680, 590, 449, 71);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chennai-600100.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(680, 530, 449, 66);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No:94,velachery main road pallikaranai,");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 460, 457, 78);

        cb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner Login", "Employee Login" }));
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel1.add(cb);
        cb.setBounds(520, 290, 265, 47);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Choose Login Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 290, 216, 47);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jash Enterprises");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 60, 662, 114);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1900, 970);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1810, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
          if(cb.getSelectedItem()=="Owner Login")
      {
          ad al=new ad();
          al.setVisible(true);
          dispose();
      }
      else
      {
          User_login ul=new User_login();
          ul.setVisible(true);
          dispose();
      }
    }//GEN-LAST:event_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
